project:
  output-dir: ./_site/tr

book:
  title: "Python Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html  
  chapters:
    - course-content/python-list-tr.md


