project:
  output-dir: ./_site/tr

book:
  output-file: "python-giris"
  title: "Python Giriş"
  chapters:
    - part: "Giriş"
      chapters:
        - index.md  
        - course-content/why-learn-python-tr.md      
        - course-content/python-range-tr.md
        - course-content/python-list-tr.md
        - course-content/python-comprehensions-tr.md
    - part: "Ekstralar"
      chapters:
        - course-content/PIP-tr.md


