project:
  output-dir: ./_site/en

book:
  output-file: "python-introduction"
  title: "Introduction to Python"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html    
  chapters:
    - part: "Introduction"
      chapters:    
        - index.md
        - intro.md
        - course-content/why-learn-python-en.md
        - course-content/references-courses-en.md
        - course-content/references-books-en.md
        #- Syllabus.md
        - course-content/online-interpreters.md
        - course-content/python-installation.md
        - course-content/programmers-text-editor.md
        - course-content/python-hello-world.md
        - course-content/command-line-en.md
        - course-content/getting-started-en.md
        - course-content/IDE-en.md
        - course-content/helpful-tools-en.md
        - course-content/debugging-en.md
        - course-content/input-function.md
        - course-content/python-built-in-functions.md
        - course-content/python-as-calculator.md
        - course-content/basic-data-types-en.md
        - course-content/variables.md

        - course-content/comparisons-boolean-variables-en.md
        - course-content/conditionals-statements-en.md

        - course-content/strings.md
        - course-content/f-strings-en.md
        - course-content/simple-function-definition.md
        - course-content/importing-modules-en.md
        - course-content/loop-intution.md
        - course-content/loop-statements-while.md
        - course-content/loop-statements-for.md
        - course-content/loop-statements.md

        - course-content/python-range-en.md
        - course-content/python-list-en.md

        - course-content/indexing-string-en.md
        - course-content/functions-en.md
        - course-content/function-arguments-en.md
        - course-content/recursion.md
        - course-content/python-dictionary.md
        - course-content/file-input-output-en.md
        - course-content/modules.md
        - course-content/PIP-en.md
        - course-content/using-other-modules-packages.md
        - course-content/exception-handling-en.md
        - course-content/python-comprehensions.md
        - course-content/useful-python-code-snippets.md
        - course-content/questions/000questions.qmd
    - part: "Extras"
      chapters:
        - course-content/virtual-environments-en.md
        - course-content/docstring-en.md
        - course-content/code-quality-style-analyzers-en.md
        - course-content/composition-en.md
        # TODO does not work in quarto, fix markdown
        #- course-content/python-object-oriented-programming.md    
    - part: "Summary"
      chapters:    
        - summary.md
        - references.md




