project:
  output-dir: ./_site/en

book:
  output-file: "python-introduction"
  title: "Introduction to Python"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html    
  chapters:
    - part: "Introduction"
      chapters:    
        - index.md
        - intro.md
        - course-content/why-learn-python.md
        - course-content/references-courses.md
        - course-content/references-books.md
        #- Syllabus.md
        - course-content/online-interpreters.md
        - course-content/python-installation.md
        - course-content/programmers-text-editor.md
        - course-content/python-hello-world.md
        - course-content/command-line.md
        - course-content/getting-started.md
        - course-content/IDE.md
        - course-content/helpful-tools.md
        - course-content/debugging.md
        - course-content/input-function.md
        - course-content/python-built-in-functions.md
        - course-content/python-as-calculator.md
        - course-content/basic-data-types.md
        - course-content/variables.md
        - course-content/comparisons-boolean-variables.md
        - course-content/conditionals-statements.md
        - course-content/strings.md
        - course-content/f-strings.md
        - course-content/simple-function-definition.md
        - course-content/importing-modules.md
        - course-content/loop-intution.md
        - course-content/loop-statements-while.md
        - course-content/loop-statements-for.md
        - course-content/loop-statements.md
        - course-content/python-range.md
        - course-content/python-list.md
        - course-content/indexing-string.md
        - course-content/functions.md
        - course-content/function-arguments.md
        - course-content/recursion.md
        - course-content/python-dictionary.md
        - course-content/file-input-output.md
        - course-content/modules.md
        - course-content/PIP.md
        - course-content/using-other-modules-packages.md
        - course-content/exception-handling.md
        - course-content/python-comprehensions.md
        - course-content/useful-python-code-snippets.md
        #- course-content/python-object-oriented-programming.md    
        - summary.md
        - course-content/questions/000questions.qmd
        - references.md




