project:
  output-dir: ./_site/tr

book:
  output-file: "python-giris"
  title: "Python Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html  
  chapters:
    - part: "Giriş"
      chapters:
        - index.md  
        - course-content/intro-tr.md
        - course-content/why-learn-python-tr.md
        - course-content/references-courses-tr.md
        - course-content/references-books-tr.md
        - course-content/online-interpreters-tr.md
        - course-content/python-installation-tr.md
        - course-content/programmers-text-editor-tr.md
        - course-content/python-hello-world-tr.md
        - course-content/python-comments-tr.md
        - course-content/command-line-tr.md
        - course-content/getting-started-tr.md
        - course-content/IDE-tr.md
        - course-content/helpful-tools-tr.md
        - course-content/debugging-tr.md
        - course-content/input-function-tr.md
        - course-content/python-built-in-functions-tr.md
        - course-content/python-as-calculator-tr.md
        - course-content/variables-tr.md
        - course-content/python-keywords-tr.md
        - course-content/basic-data-types-tr.md
        - course-content/comparisons-boolean-variables-tr.md
        - course-content/conditionals-statements-tr.md
        - course-content/strings-tr.md
        - course-content/f-strings-tr.md
        - course-content/simple-function-definition-tr.md
        - course-content/importing-modules-tr.md
        - course-content/loop-intution-tr.md
        - course-content/loop-statements-while-tr.md
        - course-content/loop-statements-for-tr.md
        - course-content/loop-statements-tr.md
        - course-content/python-range-tr.md
        - course-content/python-list-tr.md
        - course-content/indexing-string-tr.md
        - course-content/functions-tr.md
        - course-content/function-arguments-tr.md
        - course-content/recursion-tr.md
        - course-content/python-dictionary-tr.md
        - course-content/file-input-output-tr.md
        - course-content/modules-tr.md
        - course-content/using-other-modules-packages-en.md
        - course-content/exception-handling-tr.md
        - course-content/python-comprehensions-tr.md
        - course-content/useful-python-code-snippets-tr.md
        - course-content/questions/000questions-en.qmd



    - part: "Ekstralar"
      chapters:
        - course-content/PIP-tr.md
        - course-content/naming-conventions-tr.md
    - part: "Son"
      chapters:    
        - course-content/summary-tr.md
        - course-content/Sozluk-tr.qmd
        - course-content/references-tr.md


