project:
  output-dir: ./_site/tr

book:
  output-file: "python-giris"
  title: "Python Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html  
  chapters:
    - part: "Giriş"
      chapters:
        - index.md  
        - course-content/intro-tr.md
        - course-content/why-learn-python-tr.md
        - course-content/references-courses-tr.md
        - course-content/references-books-tr.md
        - course-content/online-interpreters-tr.md
        - course-content/python-installation-tr.md

        - course-content/python-range-tr.md
        - course-content/python-list-tr.md
        - course-content/python-comprehensions-tr.md
    - part: "Ekstralar"
      chapters:
        - course-content/PIP-tr.md


