# Nesne yönelimli programlama giriş

Python'daki her şey bir nesnedir.
Bir nesnenin metotlarını bulmak için **dir** fonksiyonunu kullanın


```python
type("")
dir("")


type("")
dir(1)
```

Yukarıdaki görülen str ve int sınıfları python standard kütüphanelerinde tanımlanmıştır.
Bu sayede biz bunların dahili metodlarını (fonksiyon) kullanabiliriz.


Sınıflar, nesneleri oluşturmak için kullanılan şablonlardır.

- veriler
- metotlar (sınıflara ait fonksiyonlar, çoğunlukla nesnedeki verileri kullanır)


## Dahili sınıf örnekleri

```python
adi="Atilla"
yas=50

print(type(adi))
print(type(yas))


print(adi.upper())
print(yas.bit_length())
print(yas.bit_count())
# ikili tabanda gösterimi
print(bin(yas))

```


## Yeni sınıflar tanımlama: Minimal örnek

```{.python include="course-content/Ornekler/Person0.py"}
```




## Yeni sınıflar tanımlama: yapılandırıcı

initializer method
constructor method

```{.python include="course-content/Ornekler/Person1.py"}
```



## Yeni sınıflar tanımlama:  örneklem metodları

```{.python include="course-content/Ornekler/Person2.py"}
```

## özel metodlar (dunder metodları)


-Python sınıflarının, \_\_ ile başlayan ve biten özel yöntemleri vardır.
- \_\_init\_\_ yapılandırıcı nesnelerin ilk değerlerini atama yöntemi
- \_\_str\_\_  nesnenin dizgiye dönüştürüldüğünde çalışan yöntem, örneğin print() fonksiyonunda.




### str metodunu ezme


```{.python include="course-content/Ornekler/Person3.py"}
```

### str vs repr

__repr__ ve __str__ arasındaki fark
__str__ kullanıcı dostu, __repr__ yazılımcı dostu olmalı.
Eğer kullanıcı ve yazılımcı aynı ise örneğin bir kütüphane iki kod aynı olabilir.
Ama bir web uygulamasında son kullanıcı için __str__, yazılımcı için __repr__ farklı yazılmalıdır.

```{.python include="course-content/Ornekler/Person4.py"}
```

## Referanslarımızda bu konu

- [Non-Programmer's Tutorial for Python 3/Intro to Object Oriented Programming in Python 3](https://en.wikibooks.org/wiki/Non-Programmer%27s_Tutorial_for_Python_3/Intro_to_Object_Oriented_Programming_in_Python_3)
- [Classes in Python 101](https://python101.pythonlibrary.org/chapter11_classes.html)
- [Python Classes and Objects in w3schools.com](https://www.w3schools.com/python/python_classes.asp)

## Kurs vidyo

TODO
